if type -q exa
  alias ll "exa -l -g --icons"
  alias lla "ll -a"
  alias lh "exa -l -g --icons -h"
  alias lx1 "ll --tree --level=1"
  alias lx2 "ll --tree --level=2"
  alias lx3 "ll --tree --level=3"
  alias lx4 "ll --tree --level=4"
  alias lx5 "ll --tree --level=5"
  alias lx6 "ll --tree --level=6"
  alias lx7 "ll --tree --level=7"
  alias lx8 "ll --tree --level=8"
  alias lx9 "ll --tree --level=9"
  alias lx10 "ll --tree --level=10"
  alias lx11 "ll --tree --level=11"
  alias lx12 "ll --tree --level=12"
  alias lx13 "ll --tree --level=13"
  alias lx14 "ll --tree --level=14"
  alias tr1 "exa --tree --level=1"
  alias tr2 "exa --tree --level=2"
  alias tr3 "exa --tree --level=3"
  alias tr4 "exa --tree --level=4"
  alias tr5 "exa --tree --level=5"
  alias tr6 "exa --tree --level=6"
  alias tr7 "exa --tree --level=7"
  alias tr8 "exa --tree --level=8"
  alias tr9 "exa --tree --level=9"
  alias tr10 "exa --tree --level=10"
  alias tr11 "exa --tree --level=11"
  alias tr12 "exa --tree --level=12"
  alias tr13 "exa --tree --level=13"
  alias tr14 "exa --tree --level=14"
  alias cl "clear"
  alias x "exit"
  alias tra1 "exa -a --tree --level=1"
  alias tra2 "exa -a --tree --level=2"
  alias tra3 "exa -a --tree --level=3"
  alias tra4 "exa -a --tree --level=4"
  alias tra5 "exa -a --tree --level=5"
  alias tra6 "exa -a --tree --level=6"
  alias tra7 "exa -a --tree --level=7"
  alias tra8 "exa -a --tree --level=8"
  alias tra9 "exa -a --tree --level=9"
  alias tra10 "exa -a --tree --level=10"
  alias tra11 "exa -a --tree --level=11"
  alias tra12 "exa -a --tree --level=12"
  alias tra13 "exa -a --tree --level=13"
  alias tra14 "exa -a --tree --level=14"
end
